{% set name = "ucx" %}
{% set version = "1.18.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/open{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8018dd75f11b5e8d6e57dcdb5b798d2c1f000982c353efde1f3170025c6c3b4c

build:
  number: 0
  skip: True  # [(not linux) or cuda_compiler_version in (undefined, "None", "12.6")]
  ignore_run_exports_from:
    - {{ compiler("cuda") }}
    - cuda-cudart-dev  # [cuda_compiler == "cuda-nvcc"]
  missing_dso_whitelist:
    - "*libcuda.so*"
    - "*libcudart.so*"
    - "*libnvidia-ml.so*"
  run_exports:
    - {{ pin_subpackage("ucx", max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - automake
    - autoconf
    - libtool
    - make
    - pkg-config
    - libgomp
  host:
    - cuda-version 12.4
    - cuda-cudart-dev  # [cuda_compiler == "cuda-nvcc"]
    - cuda-nvml-dev  # [cuda_compiler == "cuda-nvcc"]
    - rdma-core 58.0
  run_constrained:
    - {{ pin_compatible("cuda-version", lower_bound="11.2") }}  # [cuda_compiler == "nvcc"]
    - {{ pin_compatible("cuda-version", min_pin="x") }}  # [cuda_compiler == "cuda-nvcc"]
    # The actual version constraint comes from cuda-version, so below we explicit list
    # them only to codify that these are expected (but optional) dependencies when CUDA
    # is in use.
    - cuda-cudart  # [cuda_compiler == "cuda-nvcc"]

test:
  commands:
    - test -f "${PREFIX}/lib/libucp${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libucp.a"
    - test -f "${PREFIX}/lib/libucm${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libucm.a"
    - test -f "${PREFIX}/lib/libucs${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libucs.a"
    - test -f "${PREFIX}/lib/libuct${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libuct.a"
    - test -f "${PREFIX}/bin/.ucx-post-link.sh"
    - test -f "${PREFIX}/bin/ucx_info"
    - ucx_info -v

about:
  home: https://openucx.org
  summary: Unified Communication X.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Unified Communication X (UCX) is an award winning, optimized production-proven
    communication framework for modern, high-bandwidth and low-latency networks.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io

extra:
  recipe-maintainers:
    - marcinz
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
    - xhochy
    - pentschev
